# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package as zip
      run: |
        md release_package
        copy bin\release\* release_package
        compress-archive -Path release_package -DestinationPath  rmdup_${{github.ref_name}}.zip 
    - name : Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rmdup_${{github.ref_name}}.zip
        path: rmdup_${{github.ref_name}}.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: rmdup_${{github.ref_name}}.zip
